name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run Debug Tests
      run: ./gradlew testDebugUnitTest

    - name: Build debug
      run: bash ./gradlew build jacocoTestReport assembleAndroidTest

# Takes too long to build
#     - name: Run espresso tests
#       uses: reactivecircus/android-emulator-runner@v2 
#       with:
#         api-level: 24
#         script: ./gradlew connectedCheck
          
    - name: Upload coverage to Codecov
      run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov 
